name: Preparant a producció
run-name: ${{ github.actor }} està pujant l'aplicació a PROD 

on:
  push:
    branches:
      - main

jobs:
  Pujar-a-produccio-amb-SCP:
    runs-on: ubuntu-latest

    steps:
      - name:  Obtenint el codi del respositori
        uses: actions/checkout@v4

      - name:  Verificar variables d'entorn
        run: |
          echo "Usuari: ${{ secrets.PROD_USER }}"
          echo "Servidor: ${{ secrets.PROD_HOST }}"

      - name:  Fer SCP cap a producció
        run: |
          echo "${{ secrets.PROD_KEY }}" > ~/prod_key.pem
          chmod 600 ~/prod_key.pem
          cd ${{ github.workspace }}
          mkdir -p web
          echo "Últim desplegament fet per GitHub Actions" > web/last_deploy.txt
          date >> web/last_deploy.txt
          scp -r -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -i ~/prod_key.pem \
            index.html projectes.html web \
            ${{ secrets.PROD_USER }}@${{ secrets.PROD_HOST }}:/home/a23inbnavnav/web/ejprojectes.dam.inspedralbes.cat/public_html/
      - name:  Estat final
        run: |
          echo "Aquest job ha acabat amb l'estat: ${{ job.status }}"
